# Generated by Django 5.2.8 on 2025-11-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_date',
            field=models.DateField(blank=True, help_text='Date for the reminder', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_time',
            field=models.TimeField(blank=True, help_text='Time when you want to be reminded', null=True),
        ),
    ]
